### ISSUE TITLE
Kitty Window stays minimized, after Upgrade from 0.70.x to 0.73.x

### ISSUE THREAD

**Issue by boba23** [cyd01/KiTTY#106]
Hi everyone,

I recently tried to upgrad my rather old Kitty Version from 0.70.0.9 to the current 0.73.x.x versions.
Problem I see on my 2 Monitor setup on Windows 10 1909 is, that when I connect to any of my saved sessions or even a new one, Kitty does connect as expected, but the terminal Window never comes up on the desktop, but rather stays in the Windows taskbar, minimized. I can't restore or maximize it to show up on the desktop, it just stays minimized in the taskbar no matter what I try.
Anyone else seen this? Any suggestions on how to fix it?

Thanks,

boba

**Comment by boba23** [comment]
By the way, copying back the old version files restores functionality for me, so it must be something with the upgrade to current versions.

**Comment by systemmonkey42** [comment]
Is this still a problem for you?

There was a discussion at some point about how the window coordinates are calculated  If that changed (due to certain window layouts having negative coordinates, and the old putty ignoring those) you may find the windows are simply being placed somewhere out of reach.

Try 'moving' the windows back into view.

- Shift-right-click on the putty window in the task bar to get that windows system menu and select 'move'. (For windows 10 it might require you to hover the mouse, wait for the preview to appear and right click the preview)
- Press a cursor key (any direction), press only once.
- Start moving the mouse.

You should see the window attach itself to the mouse and move with it.
You can then place it where you want it.

I would suggest turning off the option to 'Remember Window Position'

Kind Regards

**Comment by lars18th** [comment]
Hi @boba23 ,

Please try the last version 0.73.2.3. It seems that all multimonitor troubles are fixed now.

Regards.

**Comment by boba23** [comment]
Hey guys,

sorry for the late feedback, but I've been quiet busy. Actually I could solve the problem myself before you guys answered by deleting the .ini file and let kitty create a new one.
I am pretty sure though that the windows position issue mentioned might be what caused the problem for me, can't say for sure though. It wasn't a multi-monitor issue, since I had the same problem on my notebook as well as on my pc dual monitor setup. Anyway, working fine now again with the latest release ....

thanks,

boba

**Comment by lars18th** [comment]
Hi @boba23 ,

Then please close this issue.
Thank you!

**Comment by boba23** [comment]
Hey,

I would, but GitHub won't let me sign in for like 2 days already ....

boba

**Comment by lars18th** [comment]
> Hey, I would, but GitHub won't let me sign in for like 2 days already .... boba

Ok, then we hope @cyd01 will close it.

Regards.
