### ISSUE TITLE
[RFE] Add tooltips to sessionnames in sessionlist

### ISSUE THREAD

**Issue by mjakob-gh** [cyd01/KiTTY#136]
I often use session names, which are longer than the width of the stored session "window". Showing the complete session name in a tooltip when the mouse hovers over the entry would be really helpfull.

I found this docs about tooltips in win32, but implementing it by myself, is beyond my C programming skills.
[https://docs.microsoft.com/en-us/windows/win32/controls/tooltip-controls](https://docs.microsoft.com/en-us/windows/win32/controls/tooltip-controls)

**Comment by lars18th** [comment]
Hi @mjakob-gh ,

This is similar to my request at #86 . Perhaps this idea of tooltips will be more easy to implement.

Thank you for the tip.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please can you explore this option? I have some "large" session names, and this will sove my problem described in #86 .

Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

With my large server names (including post-names with different proxy/bastion alternatives) I really need a solution.
I suggested in the past three alternatives:
1. More bigger horizontal size of the configuration window.
2. Horizontal scrollbar for the stored sessions selection.
3. Tooltips for the sessions names.

Please, comment about your preferable option.
Thank you!

**Comment by CWempe** [comment]
It would be great if the configuration window could be resized (in any direction) so it would always be the size I want. 👍 

Tooltips would be an acceptable work around, I think.

**Comment by lars18th** [comment]
Hi @CWempe ,

> It would be great if the configuration window could be resized (in any direction) so it would always be the size I want. 

Any of the three solutions are fine to me. However, regarding this one option, from the point of view of @cyd01 it's quite complex to implement. Mainly because the original window from PuTTY has _fixed_ size. So for this reason I prefer if someone implements the horizontal scrollbar, as I feel it's the most simple solution.

Regards.

**Comment by cyd01** [comment]
Some has a something to propose to fix this important issue.  
As CWempe said, everything in PuTTY config box is fixed size, so it would be complicated to add scrollbar.  
And it seems that PuTTY does not use classic Windows control to build the configuration box, so that classic tooltip functions or horizontal scrollbar does not work on it.  Don't forget they made something rather generic to work on linux too.  
So currently I have no more idea, but I really think it's a useful feature.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for your effort! I see some code in the lasts commits that is targeting scrollbars and tooltips. And it seems that doesn't work. Don't worry, perhaps in the future someone can point to a solution. For me it's sufficient that you agree that this is a useful feature and requires to be targeted.

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Any idea about how we can help you (label "help wanted") to implement this?

**Comment by cyd01** [comment]
Issue closed due to inactivity
