### ISSUE TITLE
Truncated main window due to Folders option

### ISSUE THREAD

**Issue by jradwan** [cyd01/KiTTY#14]
I reported this during the beta for 0.71 but it's still present in the final release.

When using the normal (non-portable) version, the main dialog is cut off at the bottom right-hand corner (and the window cannot be re-sized). I was told this was due to the "Folders" drop down and this could be disabled by adding "Folders=Default" to the registry. This doesn't seem to work, however. 

In the portable version, adding "Folders=Default" to the kitty.ini file _does_ work.

![image](https://user-images.githubusercontent.com/11047158/58174632-566ff200-7c6c-11e9-8424-50d648bf7827.png)

![image](https://user-images.githubusercontent.com/11047158/58174696-7a333800-7c6c-11e9-8cd9-29590ab332e1.png)

**Comment by cyd01** [comment]
There is no way to disable Folders drop down.
It does not appear in portable mode, because the feature makes no sense here. There already has directory structure for the session files.
As I was not able to reproduce the issue (see my screenshot) I've made a workaround to resize the window.
![image](https://user-images.githubusercontent.com/34154246/58176440-8c2fcd80-7ca2-11e9-9edf-2a9b89fbd009.png)

Add these lines to your kitty.ini configuration file:
```
[ConfigBox]
windowheight=800
```

**Comment by cyd01** [comment]
I've made a correction in the resize function.
Can you test this new beta: https://www.9bis.net/kitty/data/beta/kitty.exe

**Comment by bofhbug** [comment]
> It does not appear in portable mode, because the feature makes no sense here. There already has directory structure for the session files.
i wish i cut use it also in the portable version,
i use the portable version on my desktop so i have all config files in the folder without have it in the system user home.

**Comment by jradwan** [comment]
> I've made a correction in the resize function.

Much better, thank you!
