### ISSUE TITLE
Focus reporting(?) inputs weird things to kitty.exe 0.73.2.7 when switching windows

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#141]
Since 0.73.2.7, when I have a clean `vi` session open over SSH and switch to Windows Explorer and back, vi says 

> E349: No identifier under cursor

0.73.2.6 does not do that.

I don't know what is going on here, but I suspect focus reporting is doing something:
https://github.com/cyd01/KiTTY/commit/6b8133a34739615367a531be97ef85c857fc9b01

Indeed, `NoFocusReporting\1\` fixes that problem, but that's some weird default behavior.

**Comment by cyd01** [comment]
Ok: with 0.73.2.8 focus reporting is disable by default, and can be set in Terminal/Features panel.

**Comment by systemmonkey42** [comment]
> Ok: with 0.73.2.8 focus reporting is disable by default, and can be set in Terminal/Features panel.

@cyd, @lars18th 

I think I finally understand what you mean by "disabled".  

When "enabled" the feature normally does nothing, but listens for an activation escape sequence to "activate" reporting.

When "activated", Kitty sends FocusLost and FocusGained escape sequences to the application.

> vim
> :help focusgained

The application then normally "deactivates" it when it quits.

An initialisation error (fixed on 0.73.2.8) caused it to sometimes be "activated" on startup.  This
is what caused the issues you were seeing.

1. It was clearly a bug that reporting was "activated" incorrectly, whether the feature was enabled or not.  This has been fixed
2. Disabling the feature by default was an attempt to fix (1) which technically didn't work since the effect was random.

You can think of it like mouse reporting.   If mouse reporting was activated by default, it would drive everyone insane and get immediately disabled.  But since it does nothing until an application requests it, it safe to leave enabled.

**Comment by cyd01** [comment]
Issue closed due to inactivity
