### ISSUE TITLE
Don't get the chance to type password if commandline password is wrong

### ISSUE THREAD

**Issue by garnbleiche** [cyd01/KiTTY#151]
If i start kitty from commandline with a wrong password i don't get the chance to type the correct password.
Kitty Commandline (wrong password test):
`kitty-0.73.2.8 admin@x.x.x.x -pw test`

![image](https://user-images.githubusercontent.com/28215618/78379534-cceeb780-75d2-11ea-8731-389576189419.png)

If i try the same with putty i can type the right password in the putty window.
Putty Commandline (wrong password test): 
`putty admin@x.x.x.x -pw test`

![image](https://user-images.githubusercontent.com/28215618/78379747-235bf600-75d3-11ea-9988-b30af3de996f.png)

**Comment by cyd01** [comment]
Yes it works:
![image](https://user-images.githubusercontent.com/34154246/78785304-3857d100-79a7-11ea-9917-29c52f760d59.png)

But regarding you screen copy, it seems you have some device between KiTTY and you final ssh server, that break the ssh communication. Do you use a sort of man-in-the-middle authentication proxy ?
It seems in this case KiTTY can't deal with it.

I suggests you to disable the auto save password feature since you did not want it. 
Add these lines to your **%APPDATA%/KiTTY/kitty.ini** configuration file:

    [KiTTY]
    userpasssshnosave=yes

**Comment by garnbleiche** [comment]
You can close this issue!

After adding `userpasssshnosave=yes` to kitty.ini it works !

Or would it be possible that the password is only sent once? Possibly by a change in ssh2userauth.c ?
