### ISSUE TITLE
kittygen:: commandline: generate private key fails

### ISSUE THREAD

**Issue by muthusathiyanesan** [cyd01/KiTTY#157]
Resuming from Issue#116 because it was closed without correct resolution.

https://github.com/cyd01/KiTTY/issues/116

could you see the title please? I am trying to create/generate a key pair (NOT trying to open existing key).

Could you try to create a key pair from command line?

**Comment by lars18th** [comment]
Hi @muthusathiyanesan ,

First of all, I see this example from this guide: https://www.ssh.com/ssh/putty/linux/puttygen .
Then I can assume that the command line parameters are correct, even I don't use this functionality.

However, please take note that KiTTY is a **fork** of PuTTY. Then is nothing new inside it, except for the new functionalities listed in the documentation. Based on this, the `kittygen.exe` tool doesn't have new functionalities over the stock `puttygen.exe`. So, if you can't generate private keys using the KiTTY version, then try it with the PuTTY version. You only need to download the binary and save it in the same directory of KiTTY. Then use `puttygen -t rsa -b 2048 -C "user@host" -o keyfile.ppk`.

I feel that @cyd01 has closed your original issue as it is out-of-scope because the pointed reason.

Regards.

**Comment by cyd01** [comment]
I can't understantd your request.
Official PuTTY acts exactly the same.

If I run your command `puttygen -t rsa -b 2048 -C "user@host" -o keyfile.ppk` with the last [official PuTTYGen](https://the.earth.li/~sgtatham/putty/latest/w32/puttygen.exe), I get the same message:
![image](https://user-images.githubusercontent.com/34154246/79320866-c2092080-7f0a-11ea-8955-796ffa2f5c56.png)

**Comment by muthusathiyanesan** [comment]
Cyd01: I can't understand your request. Official PuTTY acts exactly the same.
[Muthu] I hoped Kitty can fix the issue. I have mentioned Putty behaves the same in my initial issue #116.
+++++++++++
PS: Oldest version 0.70.0.9 & PuttyGen also fails
+++++++++++++++

My Issue: I am writing an non-interactive command line script for which GUI won't be good.
With Windows kittygen/puttygen, to generate a key pair, I have to use 
1. PuttyGen/KittyGen GUI tool(which is interactive) or 
2. third party tool ssh-keygen(from **openssh toolset**) to create open-ssh key, then have to convert to putty key format(using **winscp.com tool**). The issue with this option is I don't want to use multiple 3rd party tool. If KittyGen can fix the issue, I could go with single tool KittyGen, for my key generation needs.
**I believe, if kittygen/puttygen wants to use a specific format for keys(.ppk), they must also provide a way to generate a key pair. I feel, it is lacking in their command line tool.**

If you think, you can't support this in Kitty, you can close this issue.

**Comment by lars18th** [comment]
Hi @muthusathiyanesan ,

As I commented before KiTTY is only a PuTTY fork. So if the original `puttygen.exe` tool doesn't have the functionality that you want then you have some alternatives:
- Ask to the original author of PuTTY to implement what you want.
- Use alternative tools for this pourpose.
- Request a new functionality here.

However, the last doesn't have sense as KiTTY focuses of **User Interface** of the **TERMINAL** tool. And only a few changes are done inside the other tools. Futhermore, personally I don't see any advantage of your request _for_ KiTTY, as it can be implemented in the stock PuTTY tool.

Sorry for not help you in this specific case.

**Comment by cyd01** [comment]
As it is still available in PuTTY for Linux, I suggest you to ask to PuTTY team to add this feature to Windows too.
