### ISSUE TITLE
Certain unicode characters not displaying

### ISSUE THREAD

**Issue by cdavoren** [cyd01/KiTTY#190]
KiTTY is not displaying (I think?) certain unicode characters that are definitely present in the selected display font.  I am encountering this problem when attempting to set up powerline for tmux.

As an example, please see the attached screenshot where the unicode symbol 0x24DB is displaying as a box/question mark when it **should** display as a circled lowercase 'L'.  This is from the tmux-powerline/segments/lan_ip.sh.  The issue persists not just in vim, but also when tmux itself is attempting to display the symbol.

The font is Fira Code, which certainly includes this glyph; it displays in word processors, for instance.

Is there a setting I should be using?

I am using KiTTY portable 0.73.2.16

![KiTTY Unicode Problem](https://user-images.githubusercontent.com/445181/83339838-b46df580-a314-11ea-89e6-983228d755e6.png)

**Comment by cdavoren** [comment]
I should add that actually I see that vanilla Fira Code does not contain this glyph; however I am using a patched version of Fira Code (from Nerd Fonts) and the problem persists.

**Comment by ahnberg** [comment]
It also exists in puTTY itself just as MobaXterm (which is also forked from puTTY) and they have similar issues.
Some additional information in this issue: https://github.com/romkatv/powerlevel10k/issues/674

I so so so wish they figure this out because these modern fancy way of using fonts is awesome, it is just very disappointing that it doesn't work in puTTY with siblings. Perhaps this is something KiTTY coders could figure out? I'd be eternally grateful!

**Comment by RomelSan** [comment]
Tested on my PC.  
The same font **Caskaydia Cove Nerd Font** will work 100% on **Windows Terminal**  
On **Kitty** will not show some icons.    
For Example:  
**Clip Ico** will show on both, type: `echo -e "\uf64e"`.  
**Folder Ico** will show only in Windows Terminal, type: `echo -e "\uf115"`  

You can download the Nerd Font here:
https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip

![Ico](https://user-images.githubusercontent.com/11341002/102135924-b027a680-3e26-11eb-8270-e3049a3e4905.PNG)

**Comment by RomelSan** [comment]
**@cyd01**
The bug is finally fixed in putty (development branch)
 It will work fine for fonts (1 character wide only) or using monospace fonts (with nerdfonts it works)
In the screenshot i am using nerdfont "hack" font.
![Fixedbug](https://user-images.githubusercontent.com/11341002/108006756-4d8b8c00-6fca-11eb-8e4d-0693a4ff5eb7.PNG)

**Comment by ahnberg** [comment]
And now finally in the release of puTTY 0.75:

"Bug fixes in this release include:
The terminal was unable to display Unicode characters in the range U+F000 to U+F1FF (part of the private-use area)."

**Comment by cyd01** [comment]
Issue closed due to inactivity
