### ISSUE TITLE
v0.73.2.17: Question about SFTP bugfix

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#194]
Hi @cyd01 ,

Why this change in the last release?
`bugfix: WinSCP integration: Do not add Proxy settings if SFTP Connect is defined`

- This implies that using SFTP the PROXY is not used? Why?
- What's the difference between SFTP and SCP regarding the proxy support?
- As it's labelled as "bugfix", what's the bug?

I ask because I don't understand it. Please, excuse me if this sounds stupid.
Regards.

**Comment by cyd01** [comment]
Sftp Connect is made to be used with a local ssh tunnel to reach the target
host

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Sftp Connect is made to be used with a local ssh tunnel to reach the target
host

Please, explain more as I don't understand it. The SSH protocol accepts two connection methods: SFTP and SCP. Futhermore, we have the plain old FTP protocol. So the WinSCP tool can be called using "sftp", "scp" or "ftp", with or without PROXY parameters. All three can be used through a proxy.

So, what means here the "Sftp Connect" mode?

**Comment by cyd01** [comment]
Before adding Proxy feature with WinSCP integration, I used to jum between
servers with ssh command plus -L tunnel to transport a local port on 2222.
I've made so many sessions like this before using Proxy.

           -L 2222:localhost:2222                              -L
2222:localhost:22
       PC ------------------------> 1st Proxy Server ---> ...
----------------------> Target Server

The WinSCP integration (to connect directly to final target) could only
work if SFTPConnect setting point to user@localhost:2222. In this case
KiTTY use this setting instead of the "Host name" in main configuration
panel. But it make no sense to use Proxy in this case (of course I could
also change all session settings to add localhost in proxy exclude list).

**Comment by lars18th** [comment]
Hi @cyd01 ,

What you're comenting seems similar to the JUMP ssh functionality. I don't know that this exists inside KiTTY. So, please can you explain if this has some influence inside the _regular_ PROXY support using SFTP, SCP or FTP when calling to the WinSCP tool?

Futhermore, if you can _extend_ this JUMP functionality it will be welcome.
Regards.

**Comment by cyd01** [comment]
I don't know what jump functionality is.
But this setting can only be use to join a local open port. So that there is no needs for proxy.
