### ISSUE TITLE
[Feature Request] Try again

### ISSUE THREAD

**Issue by eladeyal-intel** [cyd01/KiTTY#199]
Can we have a "Try again" button in this pop-up?

![image](https://user-images.githubusercontent.com/20379005/86575523-18bd4e00-bf80-11ea-891c-08440290346e.png)

**Comment by cyd01** [comment]
I've added your requested feature.
Please test this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by eladeyal-intel** [comment]
cool thanks

does not seem to work though 

![image](https://user-images.githubusercontent.com/20379005/86623884-fc92ce80-bfca-11ea-83ab-e86ee713fe74.png)

**Comment by eladeyal-intel** [comment]
@cyd01 you want to re-open the issue?

**Comment by cyd01** [comment]
It seems you use the "ugly" portable mode.
It works fine in normal mode:
[image: image.png]
I'll check what is wrong.


Le lun. 6 juil. 2020 à 19:55, eladeyal-intel <notifications@github.com> a
écrit :

**Comment by cyd01** [comment]
Found.
I've forgotten to precise I've added the feature in the Automatic reconnection patch.
So that it works if you enable it (normally it's the default), AND if you choose to allow automatic reconnection on failure. Just check the "attempt to reconnect on connection failure" in Connection panel in main configuration box. Of course you can save this setting in "Default Settings" session.
