### ISSUE TITLE
[Question] How does work pscp setting "Send file in current directory"?

### ISSUE THREAD

**Issue by FajeSu** [cyd01/KiTTY#237]
Hi!

Tell me please, how does this feature work?

- I enter the command in the terminal: `cd some_path/`
- Press `CTRL+F3` and select a file
- The file is still uploaded to the account home directory 🤷🏻‍♂️

kitty_portable v0.74.2.6
remote machine OS - Ubuntu 14.04

**Comment by cyd01** [comment]
Remember PuTTY is a text terminal. It does not known what it is on the other side: it only deals with characters in and out. So it can't know what directory you are in, because directory has no sense for text terminal. The only think I can do is to choose arbitrarily a destination. `.` (i.e. home directory) is the only one I'm pretty sure to fit everywhere.

**Comment by FajeSu** [comment]
Then how does the "Send file in current directory" function work? What is it for?
