### ISSUE TITLE
[Feature request] Confirm long text paste (as in ConEmu)

### ISSUE THREAD

**Issue by Baltazar500** [cyd01/KiTTY#261]
Hi. 

Can you make KiTTY confirm long text insertion like in ConEmu ?

![SNAGIT_2020 12 21_20 41 14_0020~01](https://user-images.githubusercontent.com/12525093/102787407-c4524180-43ec-11eb-8a96-11513bfc96db.jpg)
![SNAGIT_2020 12 21_20 41 37_0021~01](https://user-images.githubusercontent.com/12525093/102787471-da600200-43ec-11eb-8dd9-a9c55c54cc6f.jpg)

**Comment by cyd01** [comment]
I've tried to implement it. Get this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe).  
I've considered the parameter as a global setting, not a session one. So that it is configured in your **%APPDATA/KiTTY/kitty.ini** configuration file.  
Add these lines in you **[KiTTY]** section:
```
[KiTTY]
; pastesize: paste size limit (number of characters). Above the limit a confirmation is requested. (0 means unlimited)
pastesize=200
```
