### ISSUE TITLE
Need the "Clear" button in configuration window back

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [cyd01/KiTTY#293]
There used to be a "Clear" button in KiTTY's Configuration window that would clear the edit box and now it's gone. Is it possible to get it back? I saw that the button is still there in the code (`config.c`) but only shown when certain condition is met:
```c
if( !midsession && ( (get_param("INIFILE")!=2)||(!GetDirectoryBrowseFlag()) ) )
```
![image](https://user-images.githubusercontent.com/10877157/115821415-57e85d00-a435-11eb-8879-64c6fa86aea6.png)

Is it the same "Clear" button and how to make it shown? Thanks.

**Comment by EqUaTe** [comment]
Button appears for me on the latest release (0.74.4.11)

**Comment by lars18th** [comment]
I don't see this button in 0.74.4.11.
Please @EqUaTe , can you share a screenshot?

**Comment by cyd01** [comment]
"Clear" button filter is only needed when all sessions are organized in one view only without any directory structure.  
But it seems you did not organize your sessions into directories.  
Directory structure organization is the main feature in the portable mode, so that it is enable by default.  
To get the "Clear" button you must disable this feature, by either
- switch to registry mode (`savemode=registry` and download classic binary)
- remove this feature in portable mode (`browsedirectory=no`)
Add the setting in the `[KiTTY]` section of your `kitty.ini` configuration file.

**Comment by oO0oO0oO0o0o00** [comment]
Thanks. So it means I was using KiTTY in a strange way...
