### ISSUE TITLE
the .chat TLD is not correctly being seen by the link handler

### ISSUE THREAD

**Issue by HeyBanditoz** [cyd01/KiTTY#301]
Steps to reproduce:
1. Enter any link with .chat in it
2. Observe incorrect behavior
![image](https://user-images.githubusercontent.com/7574664/120255106-7d446400-c248-11eb-8d71-c48dd03cf080.png)

**Comment by cyd01** [comment]
That's why the `regex` to find url is configurable:
![image](https://user-images.githubusercontent.com/34154246/120763360-6c7d4200-c517-11eb-9568-76d5229c4116.png)

Feel free to make your own:
![image](https://user-images.githubusercontent.com/34154246/120763625-b23a0a80-c517-11eb-9bed-e7ed1d747c3d.png)

**Comment by HeyBanditoz** [comment]
Thanks!
