### ISSUE TITLE
Is it possible to specify Private Key file with relative path?

### ISSUE THREAD

**Issue by JasonSanDiego** [cyd01/KiTTY#386]
I'm using KiTTY via PortableApps and syncing across computers with Nextcloud. This is working well for having synced session settings across computers, but one issue I have is my username is not the same on all computers, so the private key file path is not the same on all computers.

It would be very useful to be able to specify the path as a relative path or with an environment variable or macro for home directory so that I can place the private key in a location relative to the KiTTY executable or in a home directory, like one of the following:
./Data/id_rsa.ppk (Data subdirectory of kitty executable)
OR
%HOME%/.ssh/id_rsa.ppk (work with different usernames on different computers)

**Comment by lars18th** [comment]
Hi @JasonSanDiego ,

I'm using a similiar environment: portable mode with a shared folder synchronized over different computers. From my point of view this is the most useful use of the portable mode. So I hope that at some point the KiTTY will promote the portable mode to the principal mode, leveraging the registry mode only to users that want to use it. Futhermore, regarding your request I vote to support it.
Regards.

**Comment by JasonSanDiego** [comment]
I came across this thread that suggests Putty has a relative path feature built into it, but I could not get it to work with KiTTY. Unclear if it's user error or didn't make it into KiTTY.
https://portableapps.com/node/5529

**Comment by lars18th** [comment]
Hi,

I need to comment that the last PuTTY 0.77 has refactored a lot the source code. So the author of KiTTY (@cyd01) will require a lot of time to implement the patches/changes to this new version. For this reason I've suggested before to spend the effort to do a change in the way hi applies the changes: The first one is to promote the PORTABLE mode to first-class support. My suggestion is to collaborate with others that are working on this: for example http://jakub.kotrla.net/putty/. This author is changing only "storage.c" and "pageant.c" for this. Then to support new version the effort is lower. However, some enhancements from KiTTY requires to be added. And the second suggestion is to isolate the different patches in chunks. Then it will be more easy to send the changes to the main developers of PuTTY. In recent moments the main developers are more open to new functionalities. The reason to refuse some of them are because at time the PuTTY source code requires a deep check for security. So only "small, clean and secure" patches are accepted. But from my point of view, some of the changes done by @cyd01 could be acceptable.

Anyway, we need to wait patienly (and support) @cyd01 to continue developing KiTTY... the best PuTTY fork ever created.

**Comment by JasonSanDiego** [comment]
Thanks for sharing that. With more testing, I was able to get it to work. It turns out that within PortableApps, KiTTY is configured with the Data subdirectory as essentially the working directory, so .\Data is redundant.

I was able to place a key in the Data directory and just write `.\id_rsa.ppk` to reference it.

From there, I was also able to get what I actually wanted - keeping the key file in my home directory - by using this to navigate up to my home folder and then into .ssh. It should continue work across computers as long my syncing folder (Nextcloud in my case) is directly within your home folder, which is pretty standard.

..\..\..\..\..\.ssh/id_rsa.ppk
