### ISSUE TITLE
Unclear where to download latest release

### ISSUE THREAD

**Issue by zdm** [cyd01/KiTTY#414]
Hi,
Thank you for the new relelease.
But unclear where we can download files.
Links on kitty site leads to the older releases.
It is possible to also publish zip archive on github releases, like you did previously?

**Comment by AntonOks** [comment]
Hi @cyd01 

Can you please continue to publish a ZIP archive on GitHub as you did before?
Because i.e. on your [Download page, alternative package managers](http://www.9bis.net/kitty/?#!pages/download.md#Alternative_installation) you mention "scoop", which again refers to the "GitHub release" zip file, which doesn't exist for the latest version :(

THANKS!

**Comment by cyd01** [comment]
Don't known why the upload did not work.  
Now it'fixed: [0.76.0.11](https://github.com/cyd01/KiTTY/releases/tag/v0.76.0.11).

**Comment by AntonOks** [comment]
> Don't known why the upload did not work. Now it'fixed: [0.76.0.11](https://github.com/cyd01/KiTTY/releases/tag/v0.76.0.11).

T H A N K    Y O U !!! :D
