### ISSUE TITLE
Crashes when Default%20Settings in AppData is symlink (only when C:/ProgramData/) is not writable?

### ISSUE THREAD

**Issue by ypid-geberit** [cyd01/KiTTY#70]
Dear @cyd01 

I first wanted to report this to https://github.com/chocolatey-community/chocolatey-coreteampackages but it is not a packaging issue. Note that Choco installs KiTTY to C:/ProgramData/Chocolatey/lib/kitty/tools/kitty.exe which is not writable for normal users. I guess the issues comes from this.

## Steps to Reproduce (for bugs)

1. Install latest version (only tried with this one): choco install kitty --params "/Portable" --version 0.73.1.1
2. Start kitty and exit out of it again (to create the `Default%20Settings` file).
3. Run this MS Shell/PowerShell code as admin:

   ```Powershell
   cd "$env:LOCALAPPDATA/VirtualStore/ProgramData/Chocolatey/lib/kitty/tools/Sessions"
   mv Default%20Settings test_file_in_git_dotfiles_repo
   new-item -Path Default%20Settings -ItemType SymbolicLink -Value test_file_in_git_dotfiles_repo | Out-Null
   ```

4. Start kitty.

## Expected Behavior

Just accept the symlink file as the default configuration.

## Current Behavior

```
Error: Unable to write session file
Directory: C:\ProgramData\Chocolatey\lib\kitty\tools\Sessions
Default%20Settings
Error code: 5
```

Note that without the symlink, KiTTY will happily fall back to the AppData path it can write to.

## Possible Solution

```Powershell
cp C:/ProgramData/Chocolatey/lib/kitty/tools/kitty.exe  C:/ProgramData/Chocolatey/lib/kitty/tools/kitty.ini "$env:LOCALAPPDATA/VirtualStore/ProgramData/Chocolatey/lib/kitty/tools/"
```

And start this kitty.exe from `%USERPROFILE%/AppData/Local/VirtualStore/ProgramData/Chocolatey/lib/kitty/tools` – it will happily accept the symlinked file.

## Context

All my important application customization live in a git repo and are symlinked (if possible) to the correct places using:

https://github.com/ypid/dotfiles/blob/master/install.ps1

This is very common on GNU/Linux, on Windows, symlinks are kinda broken but still useful when the application handles them right. KiTTY is very close to handle it right.

**Comment by CWempe** [comment]
I like this idea and would love to use it.

I tried to symlink a subfolder of `Sessions`, but Kitty cannot find any session inside that folder.

**Comment by lars18th** [comment]
Hi,

I feel the most simple solution to this problem is to catch the case when KiTTY can't write in the INI file because the main directory is readonly.

What you think it's the best workaround?
- Use an alternative fixed directory if the main directory is readonly.
- Use a command line parameter to indicate an alternative directory.
- Enforce a read-only mode without writing anything.
- Support only symlinks.

Please, comment about it.

**Comment by lars18th** [comment]
Hi,

Of this bug resolved with the last version?

**Comment by ypid-geberit** [comment]
Unfortunately not. I updated using choco.

I guess you are referring to this change: https://github.com/cyd01/KiTTY/commit/60c0dd0ad3612da447d0cc3891eff9f63f693808#diff-ee162c3dfa36997b171966ed1185bd4e
?

As I was reading it again I noticed that the starter/.lnk file specifically mentions "Start in" `%USERPROFILE%/AppData/Local/VirtualStore/ProgramData/Chocolatey/lib/kitty/tools/`. It must have something to do with that. With that starter, also the new KiTTY version works, like the old one I tested originally. Without it, also the new version does not work. Interestingly, now with: `Error code: 3`. Following that idea, I changed the starter to start `C:\ProgramData\Chocolatey\lib\kitty\tools\kitty.exe` but this workaround/test also results in the same error.

Hope this helps.

**Comment by lars18th** [comment]
Hi @ypid-geberit ,

Thank you for the description of the error. Then I feel that the only solution is to check at the start if the current directory is read-only and if it is then use and alternative path for the configuration. However, @cyd01 will need to agree with this solution.

Regards.

**Comment by ypid-geberit** [comment]
>  Then I feel that the only solution is to check at the start if the current directory is read-only and if it is then use and alternative path for the configuration.

To be clear, KiTTY already does that one correctly. It just gets confused when at the alternative path there is already a `Default%20Settings` file which happens to be a hard link (what this issue is about). Everything else already works nicely.

**Comment by lars18th** [comment]
Hi @ypid-geberit ,

> To be clear, KiTTY already does that one correctly. It just gets confused when at the alternative path there is already a `Default%20Settings` file which happens to be a hard link (what this issue is about). Everything else already works nicely.

So, any proposal to solve this problem?
I feel that if you explain for a solution then @cyd01 would want to implement it.
Regards.

**Comment by ypid-geberit** [comment]
I don’t have too much details on how to best implement this. Part of the reason is that I repressed how horrible the MS Windows is and hard links in particular.

But I can refer you to other Free Software programs, that you can look into how they handle it because KiTTY is not the first program I tried to use together with hard links. Here is my list https://github.com/ypid/dotfiles/blob/master/install.ps1 (look for `ln-s`). For example, https://conemu.github.io/ works with the hard link nicely. Both read and write.

Hope this helps.

**Comment by lars18th** [comment]
Hi @ypid-geberit ,

I agree with the concept that Windows doesn't handle **hardlinks** very good. I feel they are implemented mainly for directories, and not for files. Another question are the **softlinks**.

In any case, the problem you're experimenting is related with a the current handle of the "Default Settings". So I suggest this:

- In the current implementation, if the "Default Settings" file doesn't exists, then it is created. And if it exists then it's used. Futhermore this behaviour can be changed disabling the auto creation of the "Default Settings" file using the `kitty.ini` file.

But... I feel it's time to change this _default_ behaviour. Instead of creating the "Default Settings" if not exists, I suggest to not create it at all. Only if the `kitty.ini` indicates this. Why this have sense? Because the created file will _every_ time includes the default settings _inside_ the code. So, without this file the binary will know the default values. So it doesn't have sense to create it with the default values. Only when the users want to use this file to change the default settings, then is when it have sense.

Using this approach I feel your problem will be solved. What you think?

**Comment by ypid-geberit** [comment]
> Using this approach I feel your problem will be solved. What you think?

As far as I understand your proposal, it would not solve the underlying issue, it would just delay it. It is true that KiTTY would probably start with that change, but as soon as you try to write the "Default Settings" file, KiTTY would still crash.

You still misunderstand me. The only issue is the location from which `kitty.exe` is started. My "Default Settings" file is already a hard link and it works already with the workaround mentioned above. I just want to get rid of the workaround. Can you try to reproduce my issue on your machine?

**Comment by cyd01** [comment]
@lars18th I'm not agree with you: my personal default settings are not the same that the default ones of the PuTTY soft. I like the idea that Default Settings are initialized with "something" (whatever it is), Then I'm able to customize these settings to my personal preference. And next time I want my personal settings are available at startup ... *but it is true I don't have such issue with the registry mode*.

**Comment by cyd01** [comment]
Issue closed due to inactivity
